---
title: "Old simulations"
author: "Chris Hoover et al"
date: "4/27/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r sim_setup, echo = FALSE}
# Sim inputs
  comm_prev   <- 0.005
  days        <- 180
  dt          <- 8/24 # Resolution is an 8-hour work shift
  sim_t       <- days*(1/dt)
  exp_cases   <- numeric(length = sim_t)
  n_staff     <- 700
  staff_state <- rep("S", n_staff)

# Generate master schedule
  schedule_shifts <- rep(c("M", "E", "N"), times = days)
  schedule_days   <- rep(rep(c("U", "M", "T", "W", "R", "F", "S"), each = 3), times = ceiling(days/7))[1:length(schedule_shifts)]
  master_schedule <- paste(schedule_days, schedule_shifts, sep = "_")
```

```{r base_workers, echo = FALSE}
# Generate list of workers with no testing for model simulation
workers <- lapply(1:n_staff, function(s){
  # Worker state and infectious profile parameters for if/when they become infected  
    state <- "S"
    t_inc <- rlnorm(1, 1.63,0.5)
    t_lnt <- t_inc + runif(1, -2.5, 0)
    t_inf <- t_lnt + runif(1, 6.5, 9.5)
    
  # Worker schedule  
  # Randomly determine if worker works morning, night or day shift with equal probability  
    draw_shift <- runif(1,0,1)
    work_shift <- if_else(draw_shift < 1/3, "M",
                          if_else(draw_shift > 2/3, "N", "E"))
    
  # Randomly determine weekly schedule from four options: 1)Sat-Tues, 2)Tues-Sat,3)Thurs-Sun, 4)Mon-Thurs with eaul probability
    draw_days <- runif(1,0,1)
    work_days <- if_else(draw_days < 1/4, "SUMT",
                         if_else(draw_days > 3/4, "MTWR", 
                                 if_else(draw_days > 1/4 & draw_days < 2/4, "TWRF", "RFSU")))
    
  # Binary work schedule
    shift10 <- if_else(work_shift == schedule_shifts, 1, 0)
    work10  <- if_else(schedule_days %in% unlist(strsplit(work_days, "")), 1, 0)
    
    schedule_fin <- if_else(shift10 + work10 == 2, 1, 0)
    
   # Binary test schedule  
    test_schedule <- rep(0, sim_t)
    
  # Return worker characteristics in list  
    out                <- list()
    out$state          <- state
    out$t_latent       <- t_lnt
    out$t_incubation   <- t_inc
    out$t_infectious   <- t_inf
    out$infectiousness <- numeric()
    out$t_infect       <- -Inf
    out$work_schedule  <- schedule_fin
    out$test_schedule  <- test_schedule
    
    return(out)

})
```

```{r workers_testday1, echo = FALSE}
# Generate list of workers with testing on first day of shift for model simulation
workers_testday1 <- lapply(1:n_staff, function(s){
  # Worker state and infectious profile parameters for if/when they become infected  
    state <- "S"
    t_inc <- rlnorm(1, 1.63,0.5)
    t_lnt <- t_inc + runif(1, -2.5, 0)
    t_inf <- t_lnt + runif(1, 6.5, 9.5)
    
  # Worker schedule  
  # Randomly determine if worker works morning, night or day shift with equal probability  
    draw_shift <- runif(1,0,1)
    work_shift <- if_else(draw_shift < 1/3, "M",
                          if_else(draw_shift > 2/3, "N", "E"))
    
  # Randomly determine weekly schedule from four options: 1)Sat-Tues, 2)Tues-Sat,3)Thurs-Sun, 4)Mon-Thurs with eaul probability
    draw_days <- runif(1,0,1)
    work_days <- if_else(draw_days < 1/4, "SUMT",
                         if_else(draw_days > 3/4, "MTWR", 
                                 if_else(draw_days > 1/4 & draw_days < 2/4, "TWRF", "RFSU")))
    
  # Binary work schedule
    shift10 <- if_else(work_shift == schedule_shifts, 1, 0)
    work10  <- if_else(schedule_days %in% unlist(strsplit(work_days, "")), 1, 0)
    
    schedule_fin <- if_else(shift10 + work10 == 2, 1, 0)
    
  # Binary test schedule with test occurring on day 1 of work shift
    test_schedule <- if_else(substr(work_days,1,1) == schedule_days & work_shift == schedule_shifts,
                             1, 0 )
  
  # Return worker characteristics in list  
    out                <- list()
    out$state          <- state
    out$t_latent       <- t_lnt
    out$t_incubation   <- t_inc
    out$t_infectious   <- t_inf
    out$infectiousness <- numeric()
    out$t_infect       <- -Inf
    out$work_schedule  <- schedule_fin
    out$test_schedule  <- test_schedule
    
    return(out)

})

```

```{r sims, echo = FALSE}
n_sims <- 100

for(t in 1:sim_t){
  # Update infectious states
  states       <- unlist(lapply(workers, function(w) w$state))
  susceptibles <- sum(states == "S")
  infecteds    <- which(states == "I")
  
  for(i in infecteds){
    workers[[i]]$t_infect <- workers[[i]]$t_infect+1
    
    # Worker is recovered if past end of infectious period
    if(workers[[i]]$t_infect > length(workers[[i]]$infectiousness)){
      workers[[i]]$state <- "R"
    }
  }
  
  # New infections

  n_I <- rpois(1, comm_prev*susceptibles*dt)
  
  if(n_I > 0){
    new_Is <- which(states == "S")[1:n_I]
    
    for(i in new_Is){
      workers[[i]]$state <- "I"
      workers[[i]]$t_infect <- 0
      workers[[i]]$infectiousness <- infectious_profile(t_latent     = workers[[i]]$t_latent, 
                                                        t_peak       = workers[[i]]$t_incubation, 
                                                        t_infectious = workers[[i]]$t_infectious, 
                                                        dt           = dt)
    }
  }
  
  # Testing and isolation 
  
  # Infectious work days
  infectors_t  <- which(unlist(lapply(workers, function(w) w$state)) == "I" & 
                        unlist(lapply(workers, function(w) w$t_infect)) > 0)
  inf_work_t   <- unlist(lapply(infectors_t, function(i) workers[[i]]$work_schedule[t]))
  infectious_t <- unlist(lapply(infectors_t, function(i) workers[[i]]$infectiousness[workers[[i]]$t_infect]))
  
  exp_cases[t] <- sum(inf_work_t*infectious_t)
}
```
